import { Store } from './ts/interfaces/store';

export const store: Store = {
  cars: [],
  controls: [],
  renderPosition: {},
  inGame: false,
  totalCarsCount: 0,
  currentGaragePage: 0,
  currentWinnersPage: 0,
  winnersTable: [],
  carsBrands: [
    'Chrysler',
    'Dodge',
    'Jeep',
    'Ram',
    'Ford',
    'Lincoln',
    'Cadillac',
    'Chevrolet',
    'Tesla',
    'Audi',
    'BMW',
    'Daimler',
    'Lotec',
    'Mercedes',
    'Vauxhall',
    'Volkswagen',
    'AZLK',
    'Lada',
    'Moskvitch',
    'Volga',
  ],
  carsModels: [
    'A3',
    'Sandero',
    '2106',
    'RS',
    'e-tron',
    'TTS',
    'Golf',
    'Bulldog',
    'Pagoda',
    'DB7',
    'LeMans',
    'Aspen',
    'Cordoba',
    'Crossfire',
    'Concorde',
    'Stratus',
    'Viper',
  ],
};
