import { Store } from './ts/interfaces/store';

export const store: Store = {
  cars: [],
  countCars: 0,
  carsRaceTime: {},
  carsRace: {},
  carsHTML: {},
  editorCar: {
    carEditId: -1,
    formInputCreate: null,
    formInputEdit: null,
    inputColorCreate: null,
    inputColorEdit: null,
    btnEditorUpdate: null,
    btnEditorCreate: null,
    btnStartRace: null,
    btnResetRace: null,
    btnGaragePrevPage: null,
    btnGarageNextPage: null,
  },
  controls: {},
  renderPosition: {},
  inGame: false,

  currentGaragePage: 1,
  pagesCountGarage: 0,
  carsPerPage: 7,

  currentWinnersPage: 0,
  pagesCountWinner: 0,

  winnersTable: [],
  carsBrands: [
    'Chrysler',
    'Dodge',
    'Jeep',
    'Ram',
    'Ford',
    'Lincoln',
    'Cadillac',
    'Chevrolet',
    'Tesla',
    'Audi',
    'BMW',
    'Daimler',
    'Lotec',
    'Mercedes',
    'Vauxhall',
    'Volkswagen',
    'AZLK',
    'Lada',
    'Moskvitch',
    'Volga',
  ],
  carsModels: [
    'A3',
    'Sandero',
    '2106',
    'RS',
    'e-tron',
    'TTS',
    'Golf',
    'Bulldog',
    'Pagoda',
    'DB7',
    'LeMans',
    'Aspen',
    'Cordoba',
    'Crossfire',
    'Concorde',
    'Stratus',
    'Viper',
  ],
};
